import type { Item, DashboardStats, Haul, Profile } from '@/types'

const NOW = new Date().toISOString()
const TODAY = new Date().toISOString().slice(0, 10)
const D = (days: number) => new Date(Date.now() - days * 86400000).toISOString().slice(0, 10)

export const MOCK_ITEMS: Item[] = [
  {
    id: 'mock-1',
    status: 'acquired',
    lane: 'card',
    title: 'Charizard Base Set Holo — PSA 9',
    category: 'Pokemon Card',
    brand: 'Nintendo / Wizards of the Coast',
    model: null,
    condition_note: 'Light play, minor edge wear, strong centering',
    ai_identification: null,
    ai_confidence: 0.91,
    est_value_low: 420,
    est_value_high: 510,
    max_bid: 168,
    haul_id: 'mock-haul-1',
    lat: null,
    lng: null,
    acquired_price: 175,
    acquired_at: D(12),
    acquired_source: 'Estate sale',
    storage_location: 'Binder 1 — slot 3',
    listed_price: null,
    listed_at: null,
    ebay_item_id: null,
    sold_price: null,
    sold_at: null,
    fees: null,
    shipping_cost: null,
    notes: 'Seller didn\'t know what they had. Confirmed PSA 9 label on holder.',
    created_by: 'demo',
    created_at: NOW,
    card_details: {
      item_id: 'mock-1',
      set_name: 'Base Set',
      set_code: 'BS',
      card_number: '4/102',
      card_name: 'Charizard',
      language: 'EN',
      printing: 'Holo',
      is_graded: true,
      grader: 'PSA',
      grade: 9,
    },
    photos: [{ id: 'p1', item_id: 'mock-1', url: 'https://placehold.co/400x560/1c1917/fff?text=Charizard+PSA+9', is_primary: true, created_at: NOW }],
    comps: [
      { id: 'c1', item_id: 'mock-1', source: 'ebay_sold', price: 480, condition: 'PSA 9', sold_at: D(3), url: null, captured_at: NOW },
      { id: 'c2', item_id: 'mock-1', source: 'ebay_sold', price: 455, condition: 'PSA 9', sold_at: D(8), url: null, captured_at: NOW },
    ],
  },
  {
    id: 'mock-2',
    status: 'acquired',
    lane: 'card',
    title: 'Blastoise Base Set Holo Shadowless',
    category: 'Pokemon Card',
    brand: 'Nintendo / Wizards of the Coast',
    model: null,
    condition_note: 'NM — no visible wear, great gloss',
    ai_identification: null,
    ai_confidence: 0.84,
    est_value_low: 85,
    est_value_high: 120,
    max_bid: 34,
    haul_id: 'mock-haul-1',
    lat: null,
    lng: null,
    acquired_price: 40,
    acquired_at: D(5),
    acquired_source: 'Garage sale',
    storage_location: 'Binder 1 — slot 4',
    listed_price: null,
    listed_at: null,
    ebay_item_id: null,
    sold_price: null,
    sold_at: null,
    fees: null,
    shipping_cost: null,
    notes: null,
    created_by: 'demo',
    created_at: NOW,
    card_details: {
      item_id: 'mock-2',
      set_name: 'Base Set',
      set_code: 'BS',
      card_number: '2/102',
      card_name: 'Blastoise',
      language: 'EN',
      printing: 'Shadowless Holo',
      is_graded: false,
      grader: null,
      grade: null,
    },
    photos: [{ id: 'p2', item_id: 'mock-2', url: 'https://placehold.co/400x560/1c1917/fff?text=Blastoise+Shadowless', is_primary: true, created_at: NOW }],
    comps: [],
  },
  {
    id: 'mock-3',
    status: 'listed',
    lane: 'general',
    title: 'DeWalt DCD771C2 20V Drill — Combo Kit',
    category: 'Power Tools',
    brand: 'DeWalt',
    model: 'DCD771C2',
    condition_note: 'Like new, minimal use, original case + batteries',
    ai_identification: null,
    ai_confidence: 0.95,
    est_value_low: 110,
    est_value_high: 140,
    max_bid: 44,
    haul_id: 'mock-haul-2',
    lat: null,
    lng: null,
    acquired_price: 35,
    acquired_at: D(21),
    acquired_source: 'Garage sale',
    storage_location: 'Shelf 2',
    listed_price: 129,
    listed_at: D(14),
    ebay_item_id: '123456789012',
    sold_price: null,
    sold_at: null,
    fees: null,
    shipping_cost: null,
    notes: 'Priced below comp average to move quickly',
    created_by: 'demo',
    created_at: NOW,
    photos: [{ id: 'p3', item_id: 'mock-3', url: 'https://placehold.co/400x400/1c1917/fff?text=DeWalt+Drill', is_primary: true, created_at: NOW }],
    comps: [
      { id: 'c3', item_id: 'mock-3', source: 'ebay_sold', price: 118, condition: 'Used', sold_at: D(10), url: null, captured_at: NOW },
    ],
  },
  {
    id: 'mock-4',
    status: 'sold',
    lane: 'general',
    title: 'Nintendo Switch OLED — White, 64GB',
    category: 'Video Games',
    brand: 'Nintendo',
    model: 'Switch OLED',
    condition_note: 'Good — minor scratches on dock, screen perfect',
    ai_identification: null,
    ai_confidence: 0.97,
    est_value_low: 240,
    est_value_high: 280,
    max_bid: 96,
    haul_id: 'mock-haul-3',
    lat: null,
    lng: null,
    acquired_price: 180,
    acquired_at: D(45),
    acquired_source: 'Estate sale',
    storage_location: null,
    listed_price: 265,
    listed_at: D(40),
    ebay_item_id: '234567890123',
    sold_price: 258,
    sold_at: D(30),
    fees: 27,
    shipping_cost: 12,
    notes: null,
    created_by: 'demo',
    created_at: NOW,
    photos: [{ id: 'p4', item_id: 'mock-4', url: 'https://placehold.co/400x400/1c1917/fff?text=Switch+OLED', is_primary: true, created_at: NOW }],
    comps: [],
  },
  {
    id: 'mock-5',
    status: 'sold',
    lane: 'card',
    title: 'Pikachu Illustrator Promo JP',
    category: 'Pokemon Card',
    brand: 'Nintendo',
    model: null,
    condition_note: 'HP, heavy play — significant edge wear',
    ai_identification: null,
    ai_confidence: 0.72,
    est_value_low: 900,
    est_value_high: 1400,
    max_bid: 360,
    haul_id: 'mock-haul-4',
    lat: null,
    lng: null,
    acquired_price: 620,
    acquired_at: D(90),
    acquired_source: 'Card show',
    storage_location: null,
    listed_price: 1100,
    listed_at: D(75),
    ebay_item_id: '345678901234',
    sold_price: 980,
    sold_at: D(60),
    fees: 98,
    shipping_cost: 15,
    notes: 'HP copies still fetch strong money. Buyer was repeat customer.',
    created_by: 'demo',
    created_at: NOW,
    card_details: {
      item_id: 'mock-5',
      set_name: 'Promo',
      set_code: 'PROMO',
      card_number: null,
      card_name: 'Pikachu Illustrator',
      language: 'JP',
      printing: 'Holo',
      is_graded: false,
      grader: null,
      grade: null,
    },
    photos: [{ id: 'p5', item_id: 'mock-5', url: 'https://placehold.co/400x560/1c1917/fff?text=Pikachu+Illustrator', is_primary: true, created_at: NOW }],
    comps: [],
  },
  {
    id: 'mock-6',
    status: 'scouted',
    lane: 'general',
    title: 'Snap-on 1/2" Drive Impact Wrench',
    category: 'Power Tools',
    brand: 'Snap-on',
    model: 'MG725',
    condition_note: 'Used, functional, trigger feels sticky',
    ai_identification: null,
    ai_confidence: 0.45,
    est_value_low: 280,
    est_value_high: 380,
    max_bid: null,
    haul_id: null,
    lat: null,
    lng: null,
    acquired_price: null,
    acquired_at: null,
    acquired_source: null,
    storage_location: null,
    listed_price: null,
    listed_at: null,
    ebay_item_id: null,
    sold_price: null,
    sold_at: null,
    fees: null,
    shipping_cost: null,
    notes: 'Low confidence — model plate was partially obscured. Verify before buying.',
    created_by: 'demo',
    created_at: NOW,
    photos: [{ id: 'p6', item_id: 'mock-6', url: 'https://placehold.co/400x400/1c1917/fff?text=Snap-on+Impact', is_primary: true, created_at: NOW }],
    comps: [],
  },
  {
    id: 'mock-7',
    status: 'acquired',
    lane: 'card',
    title: 'Umbreon Gold Star — EX Unseen Forces',
    category: 'Pokemon Card',
    brand: 'Nintendo / Wizards of the Coast',
    model: null,
    condition_note: 'LP — light surface scratches, good centering',
    ai_identification: null,
    ai_confidence: 0.88,
    est_value_low: 1200,
    est_value_high: 1800,
    max_bid: 480,
    haul_id: 'mock-haul-4',
    lat: null,
    lng: null,
    acquired_price: 550,
    acquired_at: D(67),
    acquired_source: 'Card show',
    storage_location: 'Safe — envelope 2',
    listed_price: null,
    listed_at: null,
    ebay_item_id: null,
    sold_price: null,
    sold_at: null,
    fees: null,
    shipping_cost: null,
    notes: 'Holding for PSA submission window in Q1.',
    created_by: 'demo',
    created_at: NOW,
    card_details: {
      item_id: 'mock-7',
      set_name: 'EX Unseen Forces',
      set_code: 'UF',
      card_number: '17/17',
      card_name: 'Umbreon Gold Star',
      language: 'EN',
      printing: 'Gold Star Holo',
      is_graded: false,
      grader: null,
      grade: null,
    },
    photos: [{ id: 'p7', item_id: 'mock-7', url: 'https://placehold.co/400x560/1c1917/fff?text=Umbreon+Gold+Star', is_primary: true, created_at: NOW }],
    comps: [],
  },
]

export const MOCK_DASHBOARD: DashboardStats = {
  capital_tied_up: 175 + 40 + 35 + 550,
  realized_profit_month: (980 - 620 - 98 - 15),
  realized_profit_all_time: (258 - 180 - 27 - 12) + (980 - 620 - 98 - 15),
  aging_60: 1,
  aging_90: 0,
  scout_hit_rate: 0.71,
  margin_by_category: [
    { category: 'Pokemon Card', margin: 38, count: 1 },
    { category: 'Video Games', margin: 22, count: 1 },
    { category: 'Power Tools', margin: 0, count: 0 },
  ],
  window_90: {
    totals: { items: 6, spend: 1600, profit: 286, margin_pct: 36 },
    per_haul: { items: 1.5, spend: 400, profit: 71.5, margin_pct: 31 },
    haul_count: 4,
  },
}

export const MOCK_HAULS: Haul[] = [
  { id: 'mock-haul-1', created_by: 'demo', name: 'Estate sale — Elm St', lat: null, lng: null, started_at: D(12), ended_at: D(12), notes: null, created_at: D(12) },
  { id: 'mock-haul-2', created_by: 'demo', name: 'Garage sale — Maple Ave', lat: null, lng: null, started_at: D(21), ended_at: D(21), notes: null, created_at: D(21) },
  { id: 'mock-haul-3', created_by: 'demo', name: 'Estate sale — Birchwood', lat: null, lng: null, started_at: D(45), ended_at: D(45), notes: null, created_at: D(45) },
  { id: 'mock-haul-4', created_by: 'demo', name: 'Regional card show', lat: null, lng: null, started_at: D(90), ended_at: D(67), notes: null, created_at: D(90) },
]

export const MOCK_PROFILE: Profile = {
  id: 'demo',
  max_bid_pct: 40,
  ebay_ship_from_location: 'Topeka,Kansas',
  ebay_ship_from_country: 'US',
  ebay_payment_policy: null,
  ebay_shipping_policy: null,
  ebay_return_policy: null,
  created_at: NOW,
}
